# Generated by Django 4.2.5 on 2023-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0002_alter_agent_login_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent_login",
            name="agent_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
