# Generated by Django 4.2.5 on 2023-09-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0003_agent_login_agent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent_login",
            name="password",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="agent_login",
            name="agent_id",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
