# Generated by Django 4.2.5 on 2023-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0004_agent_login_password_alter_agent_login_agent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usertype", models.IntegerField()),
                ("role", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
