# Generated by Django 4.2.5 on 2023-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0005_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="login_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(default=None, max_length=100)),
                ("logintime", models.DateTimeField(auto_now_add=True)),
                ("logouttime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
